// src/components/Dashboard.jsx
import React, { useState, useRef, useEffect } from "react";
import { Bar, Line } from "react-chartjs-2";
import {
  MapContainer,
  TileLayer,
  CircleMarker,
  Popup,
  useMap,
} from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import axios from "axios";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  Tooltip,
  Legend,
  Title,
} from "chart.js";

// Register Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  Tooltip,
  Legend,
  Title,
);

// Fix Leaflet marker icons
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import markerIcon from "leaflet/dist/images/marker-icon.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: markerIcon2x,
  iconUrl: markerIcon,
  shadowUrl: markerShadow,
});

// ✅ Washington State Bounds
const WASHINGTON_BOUNDS = [
  [45.5435, -124.7631],
  [49.0024, -116.9165],
];

const WASHINGTON_CENTER = [47.7511, -120.7401];
const WASHINGTON_ZOOM = 7;

// ✅ Map Controller - Auto-zoom to new bin + Double-click with fade animation
function MapController({ bins }) {
  const map = useMap();
  const previousBinCount = useRef(0);

  // ✅ Auto-zoom to NEW bin when added (NO animation - instant)
  useEffect(() => {
    if (bins.length > previousBinCount.current && bins.length > 0) {
      const latestBin = bins[bins.length - 1];
      if (latestBin.latitude && latestBin.longitude) {
        // ✅ Direct setView - NO animation
        map.setView([latestBin.latitude, latestBin.longitude], 15);
      }
    }
    previousBinCount.current = bins.length;
  }, [bins, map]);

  // ✅ Double-click to zoom out with FADE animation
  useEffect(() => {
    const handleDoubleClick = () => {
      // Add fade effect to map container
      const mapContainer = document.querySelector(".leaflet-container");
      if (mapContainer) {
        mapContainer.style.transition = "opacity 0.5s ease";
        mapContainer.style.opacity = "0.3";

        // Zoom out to show all bins
        if (bins.length === 0) {
          map.setView(WASHINGTON_CENTER, WASHINGTON_ZOOM);
        } else if (bins.length === 1) {
          map.setView([bins[0].latitude, bins[0].longitude], 13);
        } else {
          const binCoordinates = bins
            .filter((bin) => bin.latitude && bin.longitude)
            .map((bin) => [bin.latitude, bin.longitude]);

          if (binCoordinates.length > 0) {
            const bounds = L.latLngBounds(binCoordinates);
            map.fitBounds(bounds, {
              padding: [50, 50],
            });
          }
        }

        // Fade back in after zoom
        setTimeout(() => {
          mapContainer.style.opacity = "1";
        }, 100);
      }
    };

    map.on("dblclick", handleDoubleClick);

    return () => {
      map.off("dblclick", handleDoubleClick);
    };
  }, [bins, map]);

  return null;
}

const Dashboard = () => {
  const [bins, setBins] = useState([]);
  const [binsLoading, setBinsLoading] = useState(true);

  const [kpis, setKpis] = useState([
    {
      title: "Total Waste Collected",
      value: "0.0",
      unit: "Short Tons",
      trend: "up",
      color: "#38a169",
      progress: { actual: 0, total: 1000 },
      subtitle: "Daily collection by the hour",
    },
    {
      title: "Uncollected Waste",
      value: "0.0",
      unit: "Short Tons",
      trend: "down",
      color: "#e53e3e",
      progress: { actual: 0, total: 1000 },
      subtitle: "Waste generated by the hour",
    },
    {
      title: "Average Fill Level",
      value: "0%",
      unit: " ",
      trend: "stable",
      color: "#3182ce",
      progress: { actual: 0, total: 100 },
      subtitle: "Actual Volume / Total Capacity",
    },
    {
      title: "Routes Overview",
      value: "0%",
      unit: " ",
      trend: "up",
      color: "#38a169",
      progress: { actual: 0, total: 100 },
      subtitle: "Routes in Use / Total Routes",
    },
    {
      title: "Carbon Footprint",
      value: "0.0",
      unit: "MgCO₂",
      trend: "up",
      color: "#e53e3e",
      progress: { actual: 0, total: 2000 },
      subtitle: "In MgCO₂",
    },
    {
      title: "Segregation Rate",
      value: "0%",
      unit: " ",
      trend: "up",
      color: "#38a169",
      progress: { actual: 0, total: 100 },
      subtitle: "Segregated Waste / Total Waste",
    },
    {
      title: "Electricity Generated",
      value: "0.0",
      unit: "kWh",
      trend: "up",
      color: "#3182ce",
      progress: { actual: 0, total: 1000 },
      subtitle: "In kWh",
    },
  ]);

  const [barData, setBarData] = useState({
    labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    datasets: [
      {
        label: "Reselling Revenue (in $)",
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        backgroundColor: "rgba(56, 161, 105, 0.8)",
        borderColor: "rgba(56, 161, 105, 1)",
        borderWidth: 1,
        borderRadius: 4,
        borderSkipped: false,
      },
    ],
  });

  const [lineData, setLineData] = useState({
    labels: ["9", "10", "11", "12", "13", "14", "15", "16", "17"],
    datasets: [
      {
        label: "Waste sequestered (by the hour)",
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0],
        borderColor: "#38a169",
        backgroundColor: "transparent",
        tension: 0.4,
        pointBackgroundColor: "#38a169",
        pointRadius: 3,
        fill: false,
      },
    ],
  });

  const [ticketLog, setTicketLog] = useState([]);
  const [ticketsLoading, setTicketsLoading] = useState(true);

  const barOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false }, tooltip: { enabled: true } },
    scales: {
      y: {
        beginAtZero: true,
        grid: { display: false },
        ticks: { display: false },
      },
      x: { grid: { display: false }, ticks: { color: "#4a5568" } },
    },
  };

  const lineOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false }, tooltip: { enabled: true } },
    scales: {
      y: {
        beginAtZero: true,
        grid: { display: false },
        ticks: { display: false },
      },
      x: { grid: { display: false }, ticks: { color: "#4a5568" } },
    },
  };

  const [columnWidths, setColumnWidths] = useState({
    id: 70,
    description: 280,
    comp: 100,
    sys: 90,
    date: 110,
    status: 120,
  });

  const [isResizing, setIsResizing] = useState(null);
  const [resizeStart, setResizeStart] = useState({ x: 0, width: 0 });
  const resizeRef = useRef(null);

  const columns = [
    { key: "id", label: "ID" },
    { key: "description", label: "Description" },
    { key: "comp", label: "Complete" },
    { key: "sys", label: "System" },
    { key: "date", label: "Date" },
    { key: "status", label: "Status" },
  ];

  // ✅ Calculate KPIs from Bin Data
  const calculateStatistics = (binsData) => {
    if (!binsData || binsData.length === 0) return;

    const totalBins = binsData.length;

    const totalWasteCollected = binsData.reduce((acc, bin) => {
      const binVolume = ((bin.depthCm || 100) * (bin.fillLevel || 0)) / 100;
      return acc + binVolume;
    }, 0);

    const uncollectedWaste = binsData
      .filter((bin) => bin.fillLevel >= 70 && !bin.isFlagged)
      .reduce((acc, bin) => {
        const binVolume = ((bin.depthCm || 100) * (bin.fillLevel || 0)) / 100;
        return acc + binVolume;
      }, 0);

    const avgFillLevel =
      totalBins > 0
        ? binsData.reduce((acc, bin) => acc + (bin.fillLevel || 0), 0) /
          totalBins
        : 0;

    const binsNeedingCollection = binsData.filter(
      (bin) => bin.fillLevel >= 70,
    ).length;
    const totalRoutes = Math.ceil(totalBins / 15);
    const routesInUse = Math.ceil(binsNeedingCollection / 15);
    const routesOverview =
      totalRoutes > 0 ? (routesInUse / totalRoutes) * 100 : 0;

    const carbonFootprint = (totalWasteCollected / 1000) * 0.5;

    const recyclingBins = binsData.filter(
      (bin) =>
        bin.locationName?.toLowerCase().includes("recycle") ||
        bin.locationName?.toLowerCase().includes("recycling"),
    ).length;
    const segregationRate =
      totalBins > 0 ? (recyclingBins / totalBins) * 100 : 33;

    const electricityGenerated = (totalWasteCollected / 100) * 0.5;

    setKpis([
      {
        title: "Total Waste Collected",
        value: `${(totalWasteCollected / 100).toFixed(1)}`,
        unit: "Short Tons",
        trend: totalWasteCollected > 500 ? "up" : "stable",
        color: "#38a169",
        progress: { actual: totalWasteCollected, total: 1000 },
        subtitle: "Daily collection by the hour",
      },
      {
        title: "Uncollected Waste",
        value: `${(uncollectedWaste / 100).toFixed(1)}`,
        unit: "Short Tons",
        trend: uncollectedWaste > 300 ? "down" : "stable",
        color: "#e53e3e",
        progress: { actual: uncollectedWaste, total: 1000 },
        subtitle: "Waste generated by the hour",
      },
      {
        title: "Average Fill Level",
        value: `${avgFillLevel.toFixed(0)}%`,
        unit: " ",
        trend: avgFillLevel > 70 ? "down" : avgFillLevel < 30 ? "up" : "stable",
        color: "#3182ce",
        progress: { actual: avgFillLevel, total: 100 },
        subtitle: "Actual Volume / Total Capacity",
      },
      {
        title: "Routes Overview",
        value: `${routesOverview.toFixed(0)}%`,
        unit: " ",
        trend: "up",
        color: "#38a169",
        progress: { actual: routesOverview, total: 100 },
        subtitle: "Routes in Use / Total Routes",
      },
      {
        title: "Carbon Footprint",
        value: `${carbonFootprint.toFixed(1)}`,
        unit: "MgCO₂",
        trend: "up",
        color: "#e53e3e",
        progress: { actual: carbonFootprint, total: 2000 },
        subtitle: "In MgCO₂",
      },
      {
        title: "Segregation Rate",
        value: `${segregationRate.toFixed(0)}%`,
        unit: " ",
        trend: "up",
        color: "#38a169",
        progress: { actual: segregationRate, total: 100 },
        subtitle: "Segregated Waste / Total Waste",
      },
      {
        title: "Electricity Generated",
        value: `${electricityGenerated.toFixed(1)}`,
        unit: "kWh",
        trend: "up",
        color: "#3182ce",
        progress: { actual: electricityGenerated, total: 1000 },
        subtitle: "In kWh",
      },
    ]);

    calculateChartData(binsData);
  };

  const calculateChartData = (binsData) => {
    const totalWaste = binsData.reduce((acc, bin) => {
      return acc + ((bin.depthCm || 100) * (bin.fillLevel || 0)) / 100;
    }, 0);

    const monthlyRevenue = Array.from({ length: 12 }, (_, i) => {
      const variation = 0.7 + Math.sin(i * 0.5) * 0.3;
      return Math.round(totalWaste * 0.05 * variation * 10) / 10;
    });

    setBarData({
      labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
      datasets: [
        {
          label: "Reselling Revenue (in $)",
          data: monthlyRevenue,
          backgroundColor: "rgba(56, 161, 105, 0.8)",
          borderColor: "rgba(56, 161, 105, 1)",
          borderWidth: 1,
          borderRadius: 4,
          borderSkipped: false,
        },
      ],
    });

    const hourlyWaste = Array.from({ length: 9 }, (_, i) => {
      const hour = i + 9;
      const peakFactor = 1 - Math.pow((hour - 13) / 5, 2);
      return Math.round(totalWaste * 0.1 * peakFactor * 10) / 10;
    });

    setLineData({
      labels: ["9", "10", "11", "12", "13", "14", "15", "16", "17"],
      datasets: [
        {
          label: "Waste sequestered (by the hour)",
          data: hourlyWaste,
          borderColor: "#38a169",
          backgroundColor: "transparent",
          tension: 0.4,
          pointBackgroundColor: "#38a169",
          pointRadius: 3,
          fill: false,
        },
      ],
    });
  };

  // Inside Dashboard.jsx, replace your fetchTickets function with this:

  const fetchTickets = async () => {
    try {
      const response = await axios.get(
        "http://localhost:8080/api/notifications",
      );

      // ✅ FIX: Check if data exists and is an array to prevent crashes on null response
      const notifications = response.data;
      if (!Array.isArray(notifications)) {
        console.warn(
          "Received non-array data for notifications, clearing log.",
        );
        setTicketLog([]);
        setTicketsLoading(false);
        return;
      }

      const tickets = notifications.map((notif) => ({
        id: notif.id,
        desc: notif.message || notif.title || "No description",
        comp: notif.status === "Resolved" ? "Completed" : "Pending",
        sys: notif.binId ? "System" : "User",
        date: notif.timestamp
          ? new Date(notif.timestamp).toLocaleDateString()
          : "N/A",
        status: notif.status || "Under Review",
      }));

      setTicketLog(tickets);
      setTicketsLoading(false);
    } catch (err) {
      console.error("Error fetching tickets: ", err);

      setTicketsLoading(false);
    }
  };

  const handleStatusChange = async (ticketId, newStatus) => {
    try {
      await axios.put(
        `http://localhost:8080/api/notifications/${ticketId}/status`,
        { status: newStatus },
      );

      setTicketLog(
        ticketLog.map((ticket) =>
          ticket.id === ticketId
            ? {
                ...ticket,
                status: newStatus,
                comp: newStatus === "Resolved" ? "Completed" : "Pending",
              }
            : ticket,
        ),
      );

      console.log(`Ticket ${ticketId} status updated to ${newStatus}`);
    } catch (err) {
      console.error("Error updating ticket status:", err);
      alert("Failed to update ticket status");
    }
  };

  // ✅ Fetch bins from backend
  useEffect(() => {
    const fetchBins = async () => {
      try {
        const response = await axios.get("http://localhost:8080/api/bins");
        const binsData = response.data;
        setBins(binsData);
        setBinsLoading(false);
        calculateStatistics(binsData);
      } catch (err) {
        console.error("Error fetching bins:", err);
        setBinsLoading(false);
      }
    };

    fetchBins();
    fetchTickets();

    const interval = setInterval(() => {
      fetchBins();
      fetchTickets();
    }, 30000);

    return () => clearInterval(interval);
  }, []);

  const getMarkerColor = (fillLevel, flagged) => {
    if (flagged) return "#e53e3e";
    if (fillLevel >= 90) return "#e53e3e";
    if (fillLevel >= 70) return "#dd6b20";
    if (fillLevel >= 40) return "#38a169";
    if (fillLevel > 0) return "#38a169";
    return "#718096";
  };

  const handleResizeStart = (index, e) => {
    e.preventDefault();
    const colKey = columns[index].key;
    const colWidth = columnWidths[colKey];
    setResizeStart({ x: e.clientX, width: colWidth });
    setIsResizing(index);
  };

  const handleResizeMove = (e) => {
    if (isResizing === null) return;
    const dx = e.clientX - resizeStart.x;
    const newWidth = Math.max(50, resizeStart.width + dx);
    const colKey = columns[isResizing].key;
    const newWidths = { ...columnWidths, [colKey]: newWidth };
    setColumnWidths(newWidths);
  };

  const handleResizeEnd = () => {
    setIsResizing(null);
    document.body.style.cursor = "default";
  };

  useEffect(() => {
    if (isResizing !== null) {
      document.addEventListener("mousemove", handleResizeMove);
      document.addEventListener("mouseup", handleResizeEnd);
      document.body.style.cursor = "col-resize";
    }
    return () => {
      document.removeEventListener("mousemove", handleResizeMove);
      document.removeEventListener("mouseup", handleResizeEnd);
      document.body.style.cursor = "default";
    };
  }, [isResizing, resizeStart]);

  const totalTickets = ticketLog.length;
  const resolvedTickets = ticketLog.filter(
    (t) => t.status === "Resolved",
  ).length;
  const underReviewTickets = ticketLog.filter(
    (t) => t.status === "Under Review",
  ).length;

  const getStatusBadgeStyle = (status) => {
    switch (status) {
      case "Resolved":
        return { background: "#c6f6d5", color: "#38a169" };
      case "In Progress":
        return { background: "#bee3f8", color: "#3182ce" };
      case "Under Review":
      default:
        return { background: "#fed7d7", color: "#e53e3e" };
    }
  };

  return (
    <div
      className="dashboard-page"
      style={{ backgroundColor: "white", minHeight: "100vh", padding: "20px" }}
    >
      {
        <style>{`.dashboard-page { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; } .kpi-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 15px; margin-bottom: 20px; } .kpi-card { background: white; border-radius: 8px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); height: 100%; display: flex; flex-direction: column; position: relative; } .kpi-title { font-size: 14px; color: #4a5568; margin-bottom: 8px; } .kpi-value { font-size: 24px; font-weight: 700; margin: 4px 0; color: #1a202c; } .kpi-unit { font-size: 14px; color: #4a5568; margin-top: 4px; } .kpi-subtext { font-size: 12px; color: #718096; margin-top: 8px; line-height: 1.4; min-height: 30px; } .kpi-progress { height: 8px; background: #edf2f7; border-radius: 4px; overflow: hidden; margin-top: auto; position: relative; width: 100%; } .kpi-progress-bar { height: 100%; border-radius: 4px; position: relative; transition: width 0.3s ease; } .kpi-progress-value { position: absolute; right: 0; top: -22px; font-size: 12px; color: #4a5568; } .map-container { background: #2d3748; border-radius: 8px; height: 350px; margin-bottom: 20px; position: relative; overflow: hidden; } .map-legend { position: absolute; top: 20px; right: 20px; display: flex; flex-direction: column; gap: 8px; z-index: 1000; } .legend-item { background: rgba(255,255,255,0.9); border-radius: 4px; padding: 4px 8px; font-size: 12px; color: #4a5568; display: flex; align-items: center; gap: 6px; box-shadow: 0 2px 4px rgba(0,0,0,0.2); } .legend-dot { width: 8px; height: 8px; border-radius: 50%; } .legend-gray { background: #718096; } .legend-green { background: #38a169; } .legend-orange { background: #dd6b20; } .legend-red { background: #e53e3e; } .map-scale { position: absolute; bottom: 20px; left: 20px; font-size: 12px; color: #cbd5e1; z-index: 1000; } .content-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; } .ticket-log { background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.05); } .ticket-log-header { padding: 16px; border-bottom: 1px solid #edf2f7; font-weight: 600; font-size: 18px; color: #2d3748; } .ticket-log-table { width: 100%; border-collapse: collapse; overflow-y: auto; max-height: 400px; } .ticket-log-table th { padding: 12px 16px; text-align: left; font-weight: 600; color: #4a5568; font-size: 14px; border-bottom: 1px solid #edf2f7; position: relative; min-width: 50px; } .ticket-log-table th .resize-handle { position: absolute; right: 0; top: 0; bottom: 0; width: 1px; cursor: col-resize; z-index: 10; } .ticket-log-table th:hover .resize-handle { background: #cbd5e0; } .ticket-log-table td { padding: 12px 16px; font-size: 13px; color: #2d3748; border-bottom: 1px solid #edf2f7; white-space: normal; word-break: break-word; } .ticket-log-table tr:last-child td { border-bottom: none; } .status-badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; text-transform: capitalize; font-weight: 500; border: none; cursor: pointer; transition: all 0.2s; } .status-badge:hover { opacity: 0.8; } .status-under-review { background: #fed7d7; color: #e53e3e; } .status-in-progress { background: #bee3f8; color: #3182ce; } .status-resolved { background: #c6f6d5; color: #38a169; } .status-pending { background: #feebc8; color: #dd6b20; } .chart-card { background: white; border-radius: 8px; padding: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); height: 100%; } .chart-title { font-size: 14px; font-weight: 600; color: #2d3748; margin-bottom: 12px; } .chart-container { height: 200px; } .stats-footer { display: flex; justify-content: space-between; background: white; border-radius: 8px; padding: 16px; margin-top: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); } .stat-box { text-align: center; flex: 1; } .stat-label { font-size: 14px; color: #4a5568; margin-bottom: 4px; } .stat-value { font-size: 24px; font-weight: 700; color: #1a202c; } .stat-resolved { color: #38a169; } .stat-under-review { color: #e53e3e; } .leaflet-container { background: #2d3748; border-radius: 8px; } .status-dropdown { padding: 4px 8px; border-radius: 4px; border: 1px solid #cbd5e0; font-size: 12px; font-weight: 500; cursor: pointer; background: white; transition: all 0.2s; } .status-dropdown:hover { border-color: #38a169; } .status-dropdown option { padding: 8px; }`}</style>
      }

      {/* KPI Cards */}
      <div className="kpi-grid">
        {kpis.map((kpi, i) => (
          <div key={i} className="kpi-card">
            <div className="kpi-title">{kpi.title}</div>
            <div className="kpi-value" style={{ color: kpi.color }}>
              {kpi.value}
            </div>
            <div className="kpi-unit">{kpi.unit}</div>
            <div className="kpi-subtext">{kpi.subtitle}</div>
            <div className="kpi-progress">
              <div
                className="kpi-progress-bar"
                style={{
                  width: `${(kpi.progress.actual / kpi.progress.total) * 100}%`,
                  backgroundColor: kpi.color,
                }}
              ></div>
              <div className="kpi-progress-value">
                {kpi.progress.total.toLocaleString()}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ✅ Map Section - ALWAYS VISIBLE */}
      <div className="map-container">
        {binsLoading ? (
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100%",
              color: "#cbd5e1",
            }}
          >
            Loading bins...
          </div>
        ) : (
          <MapContainer
            center={WASHINGTON_CENTER}
            zoom={WASHINGTON_ZOOM}
            maxBounds={WASHINGTON_BOUNDS}
            maxBoundsViscosity={1.0}
            minZoom={6}
            maxZoom={18}
            zoomControl={true}
            style={{ height: "100%", width: "100%" }}
          >
            <TileLayer
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            />

            {/* ✅ Map Controller - Auto-zoom + Double-click fade */}
            <MapController bins={bins} />

            {/* ✅ Render bin markers */}
            {bins.map((bin) => (
              <CircleMarker
                key={bin.id || bin.binId}
                center={[bin.latitude, bin.longitude]}
                radius={bin.fillLevel >= 90 ? 12 : bin.fillLevel >= 70 ? 10 : 8}
                fillColor={getMarkerColor(bin.fillLevel, bin.isFlagged)}
                color="#fff"
                weight={2}
                opacity={1}
                fillOpacity={0.8}
              >
                <Popup>
                  <strong>{bin.binId}</strong>
                  <br />
                  Location: {bin.locationName}
                  <br />
                  Fill Level: {bin.fillLevel}%
                  <br />
                  Status:{" "}
                  {bin.isFlagged
                    ? "🚩 Flagged"
                    : bin.fillLevel >= 90
                      ? "🔴 Critical"
                      : bin.fillLevel >= 70
                        ? "🟡 Full"
                        : "🟢 Normal"}
                </Popup>
              </CircleMarker>
            ))}

            {/* Show message when no bins */}
            {bins.length === 0 && (
              <Popup position={WASHINGTON_CENTER}>
                <div style={{ textAlign: "center" }}>
                  <strong>🗑️ No bins yet</strong>
                  <br />
                  <span style={{ fontSize: "12px", color: "#666" }}>
                    Add your first bin to start tracking
                  </span>
                  <br />
                  <a
                    href="/bins"
                    style={{ color: "#38a169", fontWeight: "600" }}
                  >
                    Add Bin →
                  </a>
                </div>
              </Popup>
            )}
          </MapContainer>
        )}

        {/* Map Legend */}
        <div className="map-legend">
          <div className="legend-item">
            <div className="legend-dot legend-gray"></div>
            <span>Empty (0%)</span>
          </div>
          <div className="legend-item">
            <div className="legend-dot legend-green"></div>
            <span>Normal (1-69%)</span>
          </div>
          <div className="legend-item">
            <div className="legend-dot legend-orange"></div>
            <span>Full (70-89%)</span>
          </div>
          <div className="legend-item">
            <div className="legend-dot legend-red"></div>
            <span>Critical (90%+)</span>
          </div>
        </div>

        <div className="map-scale">
          <div>4km</div>
          <div>2mi</div>
        </div>

        {/* ✅ REMOVED: Double-click hint label */}
      </div>

      {/* Content Section */}
      <div className="content-grid">
        {/* Ticket Log */}
        <div className="ticket-log">
          <div className="ticket-log-header">Ticket Log</div>
          {ticketsLoading ? (
            <div
              style={{ padding: "40px", textAlign: "center", color: "#718096" }}
            >
              Loading tickets...
            </div>
          ) : ticketLog.length === 0 ? (
            <div
              style={{ padding: "40px", textAlign: "center", color: "#718096" }}
            >
              No tickets generated yet
            </div>
          ) : (
            <table className="ticket-log-table">
              <thead>
                <tr>
                  {columns.map((col, index) => (
                    <th key={col.key} style={{ width: columnWidths[col.key] }}>
                      {col.label}
                      {index < columns.length - 1 && (
                        <div
                          className="resize-handle"
                          onMouseDown={(e) => handleResizeStart(index, e)}
                        />
                      )}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {ticketLog.map((t, i) => (
                  <tr key={i}>
                    <td style={{ width: columnWidths.id }}>{t.id}</td>
                    <td style={{ width: columnWidths.description }}>
                      {t.desc}
                    </td>
                    <td style={{ width: columnWidths.comp }}>{t.comp}</td>
                    <td style={{ width: columnWidths.sys }}>{t.sys}</td>
                    <td style={{ width: columnWidths.date }}>{t.date}</td>
                    <td style={{ width: columnWidths.status }}>
                      <select
                        value={t.status}
                        onChange={(e) =>
                          handleStatusChange(t.id, e.target.value)
                        }
                        className="status-dropdown"
                        style={getStatusBadgeStyle(t.status)}
                      >
                        <option value="Under Review">Under Review</option>
                        <option value="In Progress">In Progress</option>
                        <option value="Resolved">Resolved</option>
                      </select>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {/* Charts */}
        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          <div className="chart-card">
            <div className="chart-title">Reselling Revenue (in $)</div>
            <div className="chart-container">
              <Bar data={barData} options={barOptions} />
            </div>
          </div>
          <div className="chart-card">
            <div className="chart-title">Waste sequestered (by the hour)</div>
            <div className="chart-container">
              <Line data={lineData} options={lineOptions} />
            </div>
          </div>
        </div>
      </div>

      {/* Stats Footer */}
      <div className="stats-footer">
        <div className="stat-box">
          <div className="stat-label">Total Tickets</div>
          <div className="stat-value">{totalTickets}</div>
        </div>
        <div className="stat-box">
          <div className="stat-label">Resolved</div>
          <div className="stat-value stat-resolved">{resolvedTickets}</div>
        </div>
        <div className="stat-box">
          <div className="stat-label">Under Review</div>
          <div className="stat-value stat-under-review">
            {underReviewTickets}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
