// src/components/Dashboard.jsx
import React, { useState, useRef, useEffect } from "react";
import { Bar, Line } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  Tooltip,
  Legend,
  Title,
} from "chart.js";

// Register required components
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  LineElement,
  PointElement,
  Tooltip,
  Legend,
  Title,
);

const Dashboard = () => {
  // KPI Data - Now includes progress bar values
  const kpis = [
    {
      title: "Total Waste Collected",
      value: "617.0",
      unit: "Short Tons",
      trend: "up",
      color: "#38a169",
      progress: { actual: 617, total: 1000 },
      subtitle: "Daily collection by the hour",
    },
    {
      title: "Uncollected Waste",
      value: "584.0",
      unit: "Short Tons",
      trend: "down",
      color: "#e53e3e",
      progress: { actual: 584, total: 1000 },
      subtitle: "Waste generated by the hour",
    },
    {
      title: "Average Fill Level",
      value: "50%",
      unit: "",
      trend: "stable",
      color: "#3182ce",
      progress: { actual: 50, total: 100 },
      subtitle: "Actual Volume / Total Capacity",
    },
    {
      title: "Routes Overview",
      value: "43%",
      unit: "",
      trend: "up",
      color: "#38a169",
      progress: { actual: 43, total: 100 },
      subtitle: "Routes in Use / Total Routes",
    },
    {
      title: "Carbon Footprint",
      value: "1,236.0",
      unit: "MgCO₂",
      trend: "up",
      color: "#e53e3e",
      progress: { actual: 1236, total: 2000 },
      subtitle: "In MgCO₂",
    },
    {
      title: "Segregation Rate",
      value: "33%",
      unit: "",
      trend: "up",
      color: "#38a169",
      progress: { actual: 33, total: 100 },
      subtitle: "Segregated Waste / Total Waste",
    },
    {
      title: "Electricity Generated",
      value: "779.4",
      unit: "kWh",
      trend: "up",
      color: "#3182ce",
      progress: { actual: 779.4, total: 1000 },
      subtitle: "In kWh",
    },
  ];

  // Bar chart data (Reselling Revenue)
  const barData = {
    labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    datasets: [
      {
        label: "Reselling Revenue (in $S)",
        data: [872, 1229, 742, 688, 1130, 1176, 884, 1318, 528, 898, 1011, 825],
        backgroundColor: "rgba(56, 161, 105, 0.8)",
        borderColor: "rgba(56, 161, 105, 1)",
        borderWidth: 1,
        borderRadius: 4,
        borderSkipped: false,
      },
    ],
  };

  const barOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: { enabled: true },
    },
    scales: {
      y: {
        beginAtZero: true,
        grid: { display: false },
        ticks: { display: false },
      },
      x: {
        grid: { display: false },
        ticks: { color: "#4a5568" },
      },
    },
  };

  // Line chart data
  const lineData = {
    labels: ["9", "10", "11", "12", "13", "14", "15", "16", "17"],
    datasets: [
      {
        label: "Waste sequestered (by the hour)",
        data: [1694, 769, 1049, 1739, 1094, 873, 1139, 1438, 1506],
        borderColor: "#38a169",
        backgroundColor: "transparent",
        tension: 0.4,
        pointBackgroundColor: "#38a169",
        pointRadius: 3,
        fill: false,
      },
    ],
  };

  const lineOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: { enabled: true },
    },
    scales: {
      y: {
        beginAtZero: true,
        grid: { display: false },
        ticks: { display: false },
      },
      x: {
        grid: { display: false },
        ticks: { color: "#4a5568" },
      },
    },
  };

  // Ticket Log Data
  const ticketLog = [
    {
      id: "108",
      desc: "Bin sensor not reporting data",
      comp: "Completed",
      sys: "System",
      date: "10/31/2019",
      status: "Under review",
    },
    {
      id: "117",
      desc: "Bin ID 125635 at 100% fill level",
      comp: "Completed",
      sys: "System",
      date: "10/24/2019",
      status: "Resolved",
    },
    {
      id: "124",
      desc: "Add new bin sensor to system",
      comp: "Request",
      sys: "User",
      date: "09/26/2019",
      status: "Resolved",
    },
    {
      id: "127",
      desc: "Bin ID 12275 at 100% fill level",
      comp: "Completed",
      sys: "System",
      date: "10/19/2019",
      status: "Resolved",
    },
    {
      id: "128",
      desc: "Bin ID 12375 at 100% fill level",
      comp: "Completed",
      sys: "System",
      date: "10/18/2019",
      status: "Resolved",
    },
    {
      id: "133",
      desc: "Bin temperature sensor reporting unusual readings",
      comp: "Completed",
      sys: "System",
      date: "10/29/2019",
      status: "Resolved",
    },
    {
      id: "135",
      desc: "Unable to log in to Route Management System",
      comp: "Completed",
      sys: "User",
      date: "11/10/2019",
      status: "Under review",
    },
  ];

  // Draggable columns setup
  const [columnWidths, setColumnWidths] = useState({
    id: 70,
    description: 280,
    comp: 100,
    sys: 90,
    date: 110,
    status: 100,
  });

  const [isResizing, setIsResizing] = useState(null);
  const [resizeStart, setResizeStart] = useState({ x: 0, width: 0 });
  const resizeRef = useRef(null);
  const columns = [
    { key: "id", label: "ID" },
    { key: "description", label: "Description" },
    { key: "comp", label: "Complete" },
    { key: "sys", label: "System" },
    { key: "date", label: "Date" },
    { key: "status", label: "Status" },
  ];

  // Handle resize start
  const handleResizeStart = (index, e) => {
    e.preventDefault();
    const colKey = columns[index].key;
    const colWidth = columnWidths[colKey];

    setResizeStart({ x: e.clientX, width: colWidth });
    setIsResizing(index);
  };

  // Handle resize move
  const handleResizeMove = (e) => {
    if (isResizing === null) return;

    const dx = e.clientX - resizeStart.x;
    const newWidth = Math.max(50, resizeStart.width + dx);

    const colKey = columns[isResizing].key;
    const newWidths = { ...columnWidths, [colKey]: newWidth };

    setColumnWidths(newWidths);
  };

  // Handle resize end
  const handleResizeEnd = () => {
    setIsResizing(null);
    document.body.style.cursor = "default";
  };

  // Set up resize listeners
  useEffect(() => {
    if (isResizing !== null) {
      document.addEventListener("mousemove", handleResizeMove);
      document.addEventListener("mouseup", handleResizeEnd);
      document.body.style.cursor = "col-resize";
    }

    return () => {
      document.removeEventListener("mousemove", handleResizeMove);
      document.removeEventListener("mouseup", handleResizeEnd);
      document.body.style.cursor = "default";
    };
  }, [isResizing, resizeStart]);

  return (
    <div
      className="dashboard-page"
      style={{ backgroundColor: "white", minHeight: "100vh", padding: "20px" }}
    >
      <style>{`
        .dashboard-page {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        
        .kpi-grid {
          display: grid;
          grid-template-columns: repeat(7, 1fr);
          gap: 15px;
          margin-bottom: 20px;
        }
        
        .kpi-card {
          background: white;
          border-radius: 8px;
          padding: 16px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.05);
          height: 100%;
          display: flex;
          flex-direction: column;
          position: relative;
        }
        
        .kpi-title {
          font-size: 14px;
          color: #4a5568;
          margin-bottom: 8px;
        }
        
        .kpi-value {
          font-size: 24px;
          font-weight: 700;
          margin: 4px 0;
          color: #1a202c;
        }
        
        .kpi-unit {
          font-size: 14px;
          color: #4a5568;
          margin-top: 4px;
        }
        
        .kpi-subtext {
          font-size: 12px;
          color: #718096;
          margin-top: 8px;
          line-height: 1.4;
        }
        
        .kpi-trend {
          position: absolute;
          top: 16px;
          right: 16px;
          width: 12px;
          height: 12px;
          border-radius: 50%;
        }
        
        .trend-up { background: #38a169; }
        .trend-down { background: #e53e3e; }
        .trend-stable { background: #cbd5e1; }
        
        .kpi-progress {
          height: 8px;
          background: #edf2f7;
          border-radius: 4px;
          overflow: hidden;
          margin-top: 10px;
          position: relative;
        }
        
        .kpi-progress-bar {
          height: 100%;
          border-radius: 3px;
          position: relative;
        }
        
        .kpi-progress-value {
          position: absolute;
          right: 0;
          top: -22px;
          font-size: 12px;
          color: #4a5568;
        }
        
        .map-container {
          background: #2d3748;
          border-radius: 8px;
          height: 350px;
          margin-bottom: 20px;
          position: relative;
          overflow: hidden;
        }
        
        .map-placeholder {
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          color: #cbd5e1;
          font-size: 16px;
        }
        
        .map-legend {
          position: absolute;
          top: 20px;
          left: 20px;
          display: flex;
          flex-direction: column;
          gap: 8px;
        }
        
        .legend-item {
          background: rgba(255,255,255,0.7);
          border-radius: 4px;
          padding: 4px 8px;
          font-size: 12px;
          color: #4a5568;
          display: flex;
          align-items: center;
          gap: 6px;
        }
        
        .legend-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
        }
        
        .legend-green { background: #38a169; }
        .legend-blue { background: #3182ce; }
        
        .map-scale {
          position: absolute;
          bottom: 20px;
          left: 20px;
          font-size: 12px;
          color: #cbd5e1;
        }
        
        .map-footer {
          position: absolute;
          bottom: 20px;
          right: 20px;
          font-size: 10px;
          color: #cbd5e1;
        }
        
        .content-grid {
          display: grid;
          grid-template-columns: 2fr 1fr;
          gap: 20px;
        }
        
        .ticket-log {
          background: white;
          border-radius: 8px;
          overflow: hidden;
          box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        }
        
        .ticket-log-header {
          padding: 16px;
          border-bottom: 1px solid #edf2f7;
          font-weight: 600;
          font-size: 18px;
          color: #2d3748;
        }
        
        .ticket-log-table {
          width: 100%;
          border-collapse: collapse;
          overflow-y: auto;
          max-height: 400px;
        }
        
        .ticket-log-table th {
          padding: 12px 16px;
          text-align: left;
          font-weight: 600;
          color: #4a5568;
          font-size: 14px;
          border-bottom: 1px solid #edf2f7;
          position: relative;
          min-width: 50px;
        }
        
        .ticket-log-table th .resize-handle {
          position: absolute;
          right: 0;
          top: 0;
          bottom: 0;
          width: 1px;
          cursor: col-resize;
          z-index: 10;
        }
        
        .ticket-log-table th:hover .resize-handle {
          background: #cbd5e0;
        }
        
        .ticket-log-table td {
          padding: 12px 16px;
          font-size: 13px;
          color: #2d3748;
          border-bottom: 1px solid #edf2f7;
          white-space: normal;
          word-break: break-word;
        }
        
        .ticket-log-table tr:last-child td {
          border-bottom: none;
        }
        
        .status-badge {
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          text-transform: capitalize;
          font-weight: 500;
        }
        
        .status-under-review { 
          background: #fed7d7; 
          color: #e53e3e; 
        }
        
        .status-resolved { 
          background: #c6f6d5; 
          color: #38a169; 
        }
        
        .status-in-process { 
          background: #bee3f8; 
          color: #3182ce; 
        }
        
        .chart-card {
          background: white;
          border-radius: 8px;
          padding: 16px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.05);
          height: 100%;
        }
        
        .chart-title {
          font-size: 14px;
          font-weight: 600;
          color: #2d3748;
          margin-bottom: 12px;
        }
        
        .chart-container {
          height: 200px;
        }
        
        .stats-footer {
          display: flex;
          justify-content: space-between;
          background: white;
          border-radius: 8px;
          padding: 16px;
          margin-top: 20px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        }
        
        .stat-box {
          text-align: center;
          flex: 1;
        }
        
        .stat-label {
          font-size: 14px;
          color: #4a5568;
          margin-bottom: 4px;
        }
        
        .stat-value {
          font-size: 24px;
          font-weight: 700;
          color: #1a202c;
        }
        
        .stat-resolved { color: #38a169; }
        .stat-under-review { color: #e53e3e; }
      `}</style>

      {/* KPI Cards */}
      <div className="kpi-grid">
        {kpis.map((kpi, i) => (
          <div key={i} className="kpi-card">
            <div className="kpi-title">{kpi.title}</div>
            <div className="kpi-value" style={{ color: kpi.color }}>
              {kpi.value}
            </div>
            <div className="kpi-unit">{kpi.unit}</div>
            <div className="kpi-subtext">{kpi.subtitle}</div>
            <div className="kpi-trend trend-{kpi.trend}"></div>

            {/* Progress Bar */}
            <div className="kpi-progress">
              <div
                className="kpi-progress-bar"
                style={{
                  width: `${(kpi.progress.actual / kpi.progress.total) * 100}%`,
                  backgroundColor: kpi.color,
                }}
              ></div>
              <div className="kpi-progress-value">
                {kpi.progress.total.toLocaleString()}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Map Section */}
      <div className="map-container">
        <div className="map-placeholder">Map Placeholder</div>

        <div className="map-legend">
          <div className="legend-item">
            <div className="legend-dot legend-green"></div>
            <span># of Bins</span>
          </div>
          <div className="legend-item">
            <div className="legend-dot legend-blue"></div>
            <span>Bin_Location</span>
          </div>
        </div>

        <div className="map-scale">
          <div>4km</div>
          <div>2mi</div>
        </div>

        <div className="map-footer">POWERED BY esri</div>
      </div>

      {/* Content Section */}
      <div className="content-grid">
        {/* Ticket Log */}
        <div className="ticket-log">
          <div className="ticket-log-header">Ticket Log</div>
          <table className="ticket-log-table">
            <thead>
              <tr>
                {columns.map((col, index) => (
                  <th key={col.key} style={{ width: columnWidths[col.key] }}>
                    {col.label}
                    {index < columns.length - 1 && (
                      <div
                        className="resize-handle"
                        onMouseDown={(e) => handleResizeStart(index, e)}
                      />
                    )}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {ticketLog.map((t, i) => (
                <tr key={i}>
                  <td style={{ width: columnWidths.id }}>{t.id}</td>
                  <td style={{ width: columnWidths.description }}>{t.desc}</td>
                  <td style={{ width: columnWidths.comp }}>{t.comp}</td>
                  <td style={{ width: columnWidths.sys }}>{t.sys}</td>
                  <td style={{ width: columnWidths.date }}>{t.date}</td>
                  <td style={{ width: columnWidths.status }}>
                    <span
                      className={`status-badge status-${t.status.toLowerCase().replace(" ", "-")}`}
                    >
                      {t.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Charts */}
        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          <div className="chart-card">
            <div className="chart-title">Reselling Revenue (in $S)</div>
            <div className="chart-container">
              <Bar data={barData} options={barOptions} />
            </div>
          </div>

          <div className="chart-card">
            <div className="chart-title">Waste sequestered (by the hour)</div>
            <div className="chart-container">
              <Line data={lineData} options={lineOptions} />
            </div>
          </div>
        </div>
      </div>

      {/* Stats Footer */}
      <div className="stats-footer">
        <div className="stat-box">
          <div className="stat-label">Total Tickets</div>
          <div className="stat-value">13</div>
        </div>
        <div className="stat-box">
          <div className="stat-label">Resolved</div>
          <div className="stat-value stat-resolved">7</div>
        </div>
        <div className="stat-box">
          <div className="stat-label">Under Review</div>
          <div className="stat-value stat-under-review">6</div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
